# Generated by Django 4.0 on 2022-01-06 09:42

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.PositiveBigIntegerField(validators=[account.validators.validate_balance]),
        ),
    ]
