# Generated by Django 4.0 on 2021-12-30 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveBigIntegerField()),
                ('amount', models.PositiveBigIntegerField()),
                ('t_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
            options={
                'db_table': 'transaction_index_history',
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account_id', 't_type'], name='transaction_account_75d806_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account_id', 'created_at'], name='transaction_account_54259f_idx'),
        ),
    ]
