# Generated by Django 4.0 on 2022-01-06 09:42

from django.db import migrations, models
import transaction.validators


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.PositiveBigIntegerField(validators=[transaction.validators.validate_amount]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance',
            field=models.PositiveBigIntegerField(validators=[transaction.validators.validate_balance]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='t_type',
            field=models.CharField(max_length=2),
        ),
    ]
