# Generated by Django 4.0 on 2022-01-06 09:46

from django.db import migrations, models
import transaction.validators


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transaction_amount_alter_transaction_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='t_type',
            field=models.CharField(max_length=2, validators=[
                                   transaction.validators.validate_t_type]),
        ),
    ]
